Repository tylerpporter/Crate, pull requests merged in 2020-07, with the labels that each got.

#16 Add Redux dev tools
  code/web/package-lock.json
  code/web/package.json
  code/web/src/setup/store.js
Labels: enhancement

#14 Fixes rendering bug in Related component
  code/web/src/modules/product/Related.js
  code/web/src/modules/product/api/actions.js
Labels: bug

#29 Backend dk tp
  code/api/package-lock.json
  code/api/package.json
  code/api/src/config/database.json
  code/api/src/migrations/add-style-preference-to-user.js
  code/api/src/modules/user/model.js
  code/api/src/modules/user/mutation.test.js
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/user/types.js
  config/config.json
  package-lock.json
  package.json
Labels: BE, enhancement

#28 Feature/style preference
  code/web/src/modules/crate/Item.js
  code/web/src/modules/user/StylePreferences.js
  code/web/src/setup/routes/user.js
Labels: enhancement

#32 Update style preference
  code/api/package-lock.json
  code/api/package.json
  code/web/src/modules/crate/Item.js
  code/web/src/modules/user/StylePreferences.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
Labels: enhancement
